### ISSUE TITLE
Setting available page layouts doesn't work

### ISSUE THREAD

**Issue by PieterVeenstra** [OfficeDev/PnP-Sites-Core#233]
Within the BrandingExtensions.cs the following section of code doesn't look right to me:

In my case pageLayoutName is set to "_catalogs/masterpage/Featured Article Page.aspx"

           string path = "";
            if (pageLayoutName.LastIndexOf("/") > -1)
            {
                path = pageLayoutName.Substring(0, pageLayoutName.LastIndexOf("/") + 1);
            }

So now my path is "_catalogs/masterpage/

           pageLayoutName = path + System.IO.Path.GetFileNameWithoutExtension(pageLayoutName);

pageLayoutName is now set to "_catalogs/masterpage/Featured Article Page

            var masterPageGallery = web.GetCatalog((int)ListTemplateType.MasterPageCatalog);
            web.Context.Load(masterPageGallery, x => x.RootFolder.ServerRelativeUrl);
            web.Context.ExecuteQueryRetry();

            var fileRefValue = string.Format("{0}/{1}{2}", masterPageGallery.RootFolder.ServerRelativeUrl, pageLayoutName, ".aspx");

fileRefValue is now set to "/_catalogs/masterpage/_catalogs/masterpage/Featured Article Page"

My guess is that 
           pageLayoutName = path + System.IO.Path.GetFileNameWithoutExtension(pageLayoutName);

Should be replaced with:
           pageLayoutName = System.IO.Path.GetFileNameWithoutExtension(pageLayoutName);

Also isn't it better to use a different variable for the pageLayoutName that contains the name only rather than reusing the method parameter of pageLayoutName?

Currently Apply-SPOProvisioningTemplate is generating an Object reference not set to an instance of an object because of the issue above.
          

I will submit the fix for this shortly

**Comment by VesaJuvonen** [comment]
Fixed with the #234

**Comment by PieterVeenstra** [comment]
Hi Vesa,

I just tried this in the January release I'm still having the same issue.



I've got a project site ( using the project site template) as a subsite of a publishing portal. I exported it with the latest PowerShell and my publishing section in the xml looks like this:

   <pnp:Publishing AutoCheckRequirements="MakeCompliant">
        <pnp:AvailableWebTemplates>
          <pnp:WebTemplate LanguageCode="1033" TemplateName="STS#0" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="BLOG#0" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="BDR#0" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="EDISC#1" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="OFFILE#1" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="BICenterSite#0" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="CMSPUBLISHING#0" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="BLANKINTERNET#2" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="SRCHCEN#0" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="ENTERWIKI#0" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="PROJECTSITE#0" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="COMMUNITY#0" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="SRCHCENTERLITE#0" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="visprus#0" />
          <pnp:WebTemplate LanguageCode="1033" TemplateName="SAPWorkflowSite#0" />
        </pnp:AvailableWebTemplates>
        <pnp:PageLayouts />
      </pnp:Publishing>


All looks valid. I'm guessing that <pnp:PageLayouts /> means inherit from the parent site.

While the layouts are applied I can see the path looking like "/_catalogs/masterpage/_catalogs/masterpage" again.
